# src/Resources/config/doctrine/Product.orm.yml
App\Entity\Product:
  type: entity
  # ...
  manyToOne:
    category:
      targetEntity: App\Entity\User
      inversedBy: products
      joinColumn:
        nullable: false