# src/Resources/config/doctrine/Category.orm.yml
App\Entity\User:
  type: entity
  # ...
  oneToMany:
    products:
      targetEntity: App\Entity\Product
      mappedBy: email
# Don't forget to initialize the collection in
# the __construct() method of the entity